name: Tests

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  test:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [ 3.9 ]
        os:  [ macos-latest, ubuntu-latest ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          python-version: ${{ matrix.python }}
          channels: conda-forge
          channel-priority: strict
          auto-update-conda: true
          use-only-tar-bz2: true
      - name: Install conda deps
        shell: bash -l {0} #We need a login shell to get conda
        run: |
            conda install cmake pybind11
      - name: Build
        shell: bash -l {0} #We need a login shell to get conda
        run: |
            mkdir build
            cd build
            cmake ..
            make -j 2
      - name: Test
        shell: bash -l {0} #We need a login shell to get conda
        working-directory: build
        run: |
          python -c "import module.module as m; print(m.foo())"


